# Generated by Django 2.0.5 on 2018-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_produs_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='cantitate',
            field=models.IntegerField(default=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produs',
            name='pret',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
